name: Add token to Java file

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

#     - name: Build with Maven
#       run: mvn clean install

    - name: Replace token in Java file
      run: sed -i "s/TOKEN_PLACEHOLDER/$(echo ${{ secrets.TOKEN }})/g" src/App.java
