name: Add token to Java file

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup jdk
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'

#     - name: Build with Maven
#       run: mvn clean install

    - name: Replace access token in Java code
      env:
       TOKEN: "234"
      run: |
          # export ACCESS_TOKEN=${{ .ACCESS_TOKEN }}
          envsubst < WorkerApiExample.java.template > src/App.java
          cat src/App.java

#     - name: Replace token in Java file
#       env:
#        TOKEN: "234"
#       run:  |
#           sed -i "s/<your_access_token>/$(echo ${{ env.TOKEN }})/g" src/App.java
#          # sed -i "s/<your_access_token>/${{ secrets.ACCESS_TOKEN }}/g" src/App.java
        
#     - name: Display updated Java file
#       run: cat src/App.java
      
#     - name: Compile and run Java code
#       run: |
#           javac src/App.java
#           java src/App.java
